### ISSUE TITLE
Undefined array key "e" 

### ISSUE THREAD

**Issue by neptune70** [kelvinmo/simplejwt#195]
### Description

ExceptionError occurred during use of SimpleJWT library.

### Steps to reproduce

// By adding a key manually 
$set = new SimpleJWT\Keys\KeySet();

// PEM format - note raw key only, no X.509 certificates
try {
    $key = new SimpleJWT\Keys\RSAKey(file_get_contents(storage_path('************************')),'pem');
    $set->add($key);

    $headers = ['alg' => 'RSA-OAEP-256', 'enc' => 'A256GCM'];
    $plaintext = 'This is the plaintext I want to encrypt.';
    $jwt = new JWE($headers, $plaintext);
    print $jwt->encrypt($set);
} catch (RuntimeException $err) {
    print $err;
}

### Expected behaviour

We are desired to payload data using RSAKey encryption (algorithm - RSA-OAEP-256). During this process we are using the method "By adding a key manually". 

### Environment

 - Version [Laravel 10]
 - Server OS: [e.g. Ubuntu 20.04.6]
 - PHP: [8.1]
 - Packages: [
         "php": "^8.1",
        "barryvdh/laravel-dompdf": "^2.0",
        "carlos-meneses/laravel-mpdf": "^2.1",
        "dompdf/dompdf": "^2.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "laravel/ui": "^4.2",
        "maatwebsite/excel": "^3.1",
        "milon/barcode": "^10.0",
        "nwidart/laravel-modules": "^10.0",
        "spatie/laravel-permission": "^5.10",
        "spomky-labs/jose": "*"
 ]

**Comment by kelvinmo** [comment]
I cannot reproduce the error when using the RSA public key included in the tests: https://github.com/kelvinmo/simplejwt/blob/master/tests/rsa_public.pem

This suggests that the issue is with the public key you are loading with the `file_get_contents(storage_path('************************'))` part of the code

**Comment by neptune70** [comment]
How will be generate RSA public key in our server? 

And also used your RSA public key but getting error as 

UnexpectedValueException: Algorithm not supported: A256GCM in ../../vendor/kelvinmo/simplejwt/src/SimpleJWT/Crypt/AlgorithmFactory.php:97........

**Comment by kelvinmo** [comment]
You can generate an RSA key pair using the following OpenSSL commands:

```shell
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -out public.pem -pubout
```

If you are getting an "Algorithm not supported" error for `A256GCM` when trying to create a JWE, this may be due to an old version of PHP, or the openssl PHP extension not supporting AES GCM.

To check, you can run the following code to list out all the encryption methods supported by your OpenSSL extension:

```php
echo implode("\n", openssl_get_cipher_methods());
```

If you can't find `aes-256-gcm` in that list, then `A256GCM` is not supported by your PHP installation.

**Comment by neptune70** [comment]
Thanks a lot @kelvinmo
