### ISSUE TITLE
composer dependencies

### ISSUE THREAD

**Issue by morozovsk** [kelvinmo/simplejwt#22]
kelvinmo/simplejwt v0.4.0 requires symfony/console ~2.8 but it is too much old

[symfony/yaml](https://packagist.org/packages/symfony/yaml) conflicts symfony/console <4.4

**Comment by kelvinmo** [comment]
I've updated composer.json so that symfony/console can pick up ^4.0 instead of 2.8, which is retained for PHP5 compatibility.

Given symfony/console is only used for the jwkstool, another option is to move that package from `required` to `suggest`, so that those who don't need to use jwkstool don't need to install it.
